server.port=8080

#----MYSQL CONFIG
spring.datasource.url=${DB_URL}
# CREDENCIALES
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#----JPA
spring.jpa.hibernate.ddl-auto=update

#----ERROR
spring.web.error.include-message=always

#----KEYCLOACK
keycloak.server-url=${KEYCLOACK_BASE_URL}
keycloak.realm=${KEYCLOACK_REALM}
keycloak.client-id=${KEYCLOACK_CLIENT_ID}
keycloak.client-secret=${KEYCLOACK_SECRET}