server.port=8080

#----MYSQL CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
# CREDENCIALES
spring.datasource.username=root
spring.datasource.password=1234
# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#----JPA
spring.jpa.hibernate.ddl-auto=update

#----ERROR
spring.web.error.include-message=always
